### ISSUE TITLE
EIF supports the latest macOS Big Sur？

### ISSUE THREAD

**Issue by 1115475664** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#1]
My computer is 7050mt, other functions are normal，  But  Mic cannot be used！The system is 10.15.7.Is your mic normal? thank you. I'm from China.

**Comment by linkev** [comment]
> My computer is 7050mt, other functions are normal， But Mic cannot be used！The system is 10.15.7.Is your mic normal? thank you. I'm from China.

Hi, I'm not sure if my mic also works as I don't have a 3.5mm mic to test with, it might be worth to change the alcid=11 to a different number, I usually use a USB microphone so that could be an alternative to you. Also, BIOS might be a problem as well, you never know. If I find something, I will let you know :)

Edit: I haven't tried Big Sur as I am waiting for the public release, but I imagine it will work as everything is almost perfect on Catalina.

**Comment by 1115475664** [comment]
Thank you. The latest MacOS Big Sur was upgraded last night. It looks like everything's OK. I also plan to use USB mic. Thank you for sharing. thank you
