### ISSUE TITLE
An Error Occurred While Preparing the Software Update

### ISSUE THREAD

**Issue by AshkanAbd** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#20]
I'm trying to install Ventura (also tried Sonoma) on my Dell OptiPlex 7050 mini using iMac 18.1 SMBios (also tried mac mini 8.1), I've listed my pc specs below. After selecting my SSD as installation drive, the installation starts but after first reboot (before the installation process was completed), I keep getting this error at the end of the Ventura install.

OpenCore is clearly running as I have a boot picker and the install goes through with no errors, but now it boots from the SSD and gives me 30 minutes remaining, and then this.

My specs:
Dell OptiPlex 7050 mini
CPU: 7700T
Ram: 16GB
SSD: 256GB

I also applied bios and UEFI configurations and reset NVRam, but I still got this error.
Please help me to fix this issue.

![error](https://github.com/linkev/Dell-Optiplex-7050-Micro-Hackintosh/assets/29902791/846e6201-10cc-4012-bcd9-e3b0a1972725)

**Comment by linkev** [comment]
Hey @AshkanAbd Hmm, never seen this screen before, from a first glance, I'm guessing you may be using the online updater and not the full installer (usually a 12GB download from the Mac App Store). If you have a Mac or Hackintosh on hand you could use: https://github.com/ninxsoft/Mist

It's supposed to go straight into asking you to install macOS or doing something with Disk Utility.

Otherwise, if you made this installer in Windows, you may want to redo the instructions here: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#making-the-installer

Also, would recommend to temporarily disable anything to do with WiFi, just until you're fully installed. Sonoma doesn't support the Dell WiFi card I used in the current guide, in the process of updating the entire repo for Sonoma and using an Intel card with https://github.com/OpenIntelWireless/itlwm

Let me know how it goes 😄

**Comment by AshkanAbd** [comment]
I have no wifi card at all, Also I disabled them in config.plist. 
And I've tested different installers from different sources (App store, Mist, etc).
I still face this odd issue, I have no idea about it.
I changed my usb stick, the whole my pc but nothing changes at all.

What do you think about it?

**Comment by linkev** [comment]
@AshkanAbd What brand is your SSD? I believe anthing Samsung is broken, ideally you would use a Sabrent drive if possible as that is natively supported (I think WD is good too, need to research that). I'm thinking it could be that, I remember having install issues when using PM981 drives that these Dell's used to come with

**Comment by AshkanAbd** [comment]
@linkev Yes, my SSD caused this issue, I replaced it with a Adata SSD.
I've updated OC to 1.0.0 and applied few other changes.
Please check my [PR](https://github.com/linkev/Dell-Optiplex-7050-Micro-Hackintosh/pull/22)
I have wifi issue but other things are working fine.

**Comment by linkev** [comment]
@AshkanAbd Glad to hear it works for you now 😄 I'm in the middle of updating as well, thanks for your PR! I am implementing OpenCanopy like you did as well, as for the WiFi not working for you, it's because Sonoma dropped support for Broadcom WiFi cards, meaning DW1560 or DW1820a etc. is not going to work unless you disable SIP and patch it with OpenCorePatcher: https://dortania.github.io/OpenCore-Legacy-Patcher/

I haven't tried it myself, so I have changed the WiFi card for myself over Intel and will be changing the repo to support that. Its a shame, but if people want to they can patch Broadcom themselves. Going with Intel to keep the SIP enabled for security and ease of use purposes, its just a simple kext.
