### ISSUE TITLE
Why mac mini smbios?

### ISSUE THREAD

**Issue by kymerea** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#23]
Hi there, with your recent update I've noticed the change to the macmini8,1 smbios which makes sense since iMac18,1 and lower got dropped in sonoma but why specifically macmini8,1? Does it provide any benefits over chosing something like iMac19,1?

**Comment by linkev** [comment]
Hey @ItxWeird Honestly I forget, I was using Macmini8,1 for a while now and I believe it was because it's the closest setup GPU wise, a legit Mac mini has Intel UHD 630 while my i7-7700 has Intel HD 630. That and it does make more sense for this Optiplex Micro form factor to mimic an actual Mac mini, you have to plug in a monitor etc. rather than having a hardwired one like the iMac. Someone on Reddit was having random restarts when not on a Macmini SMBIOS, it might have been happening to me too: https://www.reddit.com/r/hackintosh/comments/d5svdu/comment/f0nw2em/

iMac18,1 doesn't make sense anymore since I think macOS Sequoia dropped support for it, while Macmini8,1 still remains (although it needs a T2 chip, we'll see if it runs at all).

You might be onto something with that iMac19,1 call, all the CPU's in it have UHD630 so graphics should be fine, other things don't really matter. I might give it a go the next time I feel like reinstalling or let me know if you try it and it works out for you, happy to change over if it's the same or better 😃

**Comment by kymerea** [comment]
Ah okay, it does make sense, I'm going to have to reinstall to get macOS sonoma working since I was originally on iMac18,1, I might give Macmini8,1 a go or iMac19,1 goes, I will let you know how it goes.
