### ISSUE TITLE
DP and HDMI rev are flipped 

### ISSUE THREAD

**Issue by tomten1** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#3]
DP and HDMI revision are flipped in the first part of the guide.

**Comment by linkev** [comment]
Hi, I double checked and it seems correct, its listed as DisplayPort 1.2 on [Dell's website](https://www.dell.com/support/manuals/en-uk/optiplex-7050-desktop/optiplex-7050-desktop-micro-owners-manual/ports-and-connectors-specifications?guid=guid-fa18be33-104b-4859-a7f7-59b9314d348c&lang=en-us).

Same with HDMI 1.4, its limited to [3840 × 2160 at 24, 25, and 30 Hz](https://en.wikipedia.org/wiki/HDMI#Version_1.4), which is what happens when I plug it into my 4K TV.

I have to use a DisplayPort to HDMI 2.0 active adapter to get 4K 60FPS output from this computer. Blame the standards for naming their revisions in a confusing way! 😊

Ninja Edit: You were right, its in the second part of the Readme, where it said what's working, changing it now, sorry!
