### ISSUE TITLE
About the problem after disabling BD PROCHOT

### ISSUE THREAD

**Issue by dxb134111** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#8]
After I disable BD PROCHOT with the step_var command, when my mini host uses Windows10, the cpu frequency is still 0.79Ghz, and my power adapter is 130w, not the original Dell. By the way, my host is 7050mff and the cpu is i7 6700, can you please fix this? Looking forward to your reply! thank you very much!

**Comment by linkev** [comment]
@dxb134111 Hi, sorry for the delay on this, I'm assuming by "step_var" you mean "setup_var"? It may well be that it doesn't do what I think it does, I just put the info there because when my CPU on the Optiplex 7050 Micro got locked to 0.79Ghz, I'd already dumped the BIOS and found that there is a BD PROCHOT switch.

I did the setup_var command and it fixed my problem after restart. I am using a legitimate Dell 130W power adapter though, so maybe that's why? Dell are very picky about what you use and its hard to bypass (just look at their XPS line).

As for the 7050 MFF version, there shouldn't be many differences between the normal version and my "Optiplex Micro" version (maybe some audio differences and more USB ports to map, but they're all relatively the same).

**Comment by dxb134111** [comment]
ok thank you very much for your reply

**Comment by ghost** [comment]
In the case of my Optiplex 7050 Micro with an i5-6500T, the culprit was the firmware setting the CPU base frequency to 0.79 GHz and writing 0x4000850089 to MSR 0x1a0 at startup, disabling Turbo Boost, despite turbo boost being enabled within the setup utility. The solution is to write 0x850089 to 0x1a0 at startup, which re-enables Turbo Boost.

**Comment by dxb134111** [comment]
> 对于我的带有 i5-6500T 的 Optiplex 7050 Micro，罪魁祸首是固件将 CPU 基本频率设置为 0.79 GHz 并在启动时将 0x4000850089 写入 MSR 0x1a0，禁用 Turbo Boost，尽管在设置实用程序中启用了 Turbo Boost。解决方案是在启动时写入 0x850089 到 0x1a0，从而重新启用 Turbo Boost。

Thank you very much for your reply, do you have specific steps? Looking forward for your reply, thank you
